.TH EJABBERDCTL "8" "September 2016" "ejabberd 16.09" "ejabberdctl manual page"
.SH NAME
ejabberdctl \- control interface for the ejabberd Jabber/XMPP server
.SH SYNOPSIS
.B ejabberdctl
[\fI\,--no-timeout\/\fR] [\fI\,--node nodename\/\fR] [\fI\,--version api_version\/\fR] \fI\,command \/\fR[\fI\,options\/\fR]
.SH DESCRIPTION
.PP
\fBejabberdctl\fR  is a front end to the ejabberd Jabber/XMPP server.
It is designed to help the administrator control the functioning of the
running \fBejabberd\fR daemon.
.PP
This command must be run either by a superuser or by the user \fBejabberd\fP,
otherwise it will fail to start or to connect to the ejabberd instance. Using sudo also works.
.SH COMMANDS
.PP
To get a list of available commands for the given ejabberd node, simply run \fBejabberdctl\fR without any command.

Of course the given ejabberd node needs to be up and running for this to succeed.
.SH NOTES
.PP
\fBejabberdctl\fR does not do anything by itself except for connecting
to the running ejabberd instance and telling it about the action requested
by the user. Hence all the \fBejabberdctl\fR's operations involving
writing or reading files or directories are actually performed by the
server process which runs with the uid and gid of the user and group
"ejabberd". This must be taken into account when requesting such operations
to be done.
.SH OPTIONS FILE
.PP
.TP
.BI ERLANG_NODE
Use specified string as Erlang node of \fBejabberd\fP server to connect. It
overrides default \fBejabberd\fP node name. The string may take one of the
following forms: \fBnodename\fP, \fBnodename@hostname\fP or
\fBnodename@hostname.domainname\fP.
.TP
.BI FIREWALL_WINDOW
Use the specified range of ports to communicate with the other Erlang
nodes (namely, with the target Erlang node running ejabberd).
This can be useful when the system running the target node has restricted
firewall setup allowing only a certain range of ports to be used by
the Erlang nodes for communication; in this case, you should specify
that range of ports in the \fBFIREWALL_WINDOW\fR setting.
.SH FILES
.PP
.TP
.BI /etc/default/ejabberd
Default settings for ejabberdctl which is also run by systemd / the init script
.TP
.BI /etc/ejabberd
Configuration directory
.TP
.BI /etc/ejabberd/ejabberd.yml
Main configuration file
.TP
.BI /var/log/ejabberd
Logfile directory
.TP
.BI /var/lib/ejabberd
Database spool directory
.SH SEE ALSO
.PP
\fBerl\fR(1), \fBmnesia\fR(3).
.PP
The program documentation is available at
\fIhttp://www.process\-one.net/en/projects/ejabberd/\fP.
.SH AUTHORS
.PP
This manual page was adapted by Sergei Golovan <sgolovan@nes.ru> for
the \fBDebian\fP system (but may be used by others) from the
\fBejabberd\fP documentation written by Alexey Shchepin <alexey@sevcom.net>.
Updated by Konstantin Khomoutov <flatworm@users.sourceforge.net> and
Philipp Huebner <debalance@debian.org>.

Permission is granted to copy, distribute and/or modify this document under
the terms of the GNU General Public License, Version 2 any
later version published by the Free Software Foundation.
.PP
On Debian systems, the complete text of the GNU General Public
License can be found in /usr/share/common\-licenses/GPL-2.
