#!/bin/sh

set -e

case "$1" in
	install)
		# Create /etc/ejabberd if it doesn't already exist
		mkdir -p /etc/ejabberd
		# Ejabberd config dir may contain sensitive data, so making it unreadable by
		# the world.
		if ! dpkg-statoverride --list /etc/ejabberd >/dev/null; then
			chmod 750 /etc/ejabberd
		fi

		# Create a certificate and store it in /etc/ejabberd
		echo "Generating SSL certificate /etc/ejabberd/ejabberd.pem..."
		EHOSTNAME=$(hostname -s 2>/dev/null || echo localhost)
		EDOMAINNAME=$(hostname -d 2>/dev/null || echo localdomain)
		openssl req -new -x509 -days 365 -nodes -out /etc/ejabberd/ejabberd.pem \
			-keyout /etc/ejabberd/ejabberd.pem > /dev/null 2>&1 <<+++
.
.
.
$EDOMAINNAME
$EHOSTNAME
ejabberd
root@$EHOSTNAME.$EDOMAINNAME
+++

		# Ejabberd cert should have appropriate permissions so as to not be readable
		# by the world.
		if [ -f /etc/ejabberd/ejabberd.pem ]
		then
			if ! dpkg-statoverride --list /etc/ejabberd/ejabberd.pem >/dev/null; then
				chmod 640 /etc/ejabberd/ejabberd.pem
			fi
		fi
		;;

	upgrade|abort-upgrade)
		;;

	*)
		echo "postinst called with unknown argument \`$1'" >&2
		exit 0
		;;
esac

#DEBHELPER#

exit 0
