#! /bin/sh
# prerm script for ejabberd
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <prerm> `remove'
#        * <old-prerm> `upgrade' <new-version>
#        * <new-prerm> `failed-upgrade' <old-version>
#        * <conflictor's-prerm> `remove' `in-favour' <package> <new-version>
#        * <deconfigured's-prerm> `deconfigure' `in-favour'
#          <package-being-installed> <version> `removing'
#          <conflicting-package> <version>
# for details, see /usr/doc/packaging-manual/

ctl() {
	local cmd='/usr/sbin/ejabberdctl'
	for arg in "$@"; do
		cmd="$cmd '$arg'"
	done
	su ejabberd -c "$cmd"
}

case "$1" in
    remove|upgrade)
	if ctl status >/dev/null ; then
	    # Use timestamp to make database restoring easier
	    TIME=$(date +%Y-%m-%dT%H:%M:%S)
	    BACKUPDIR=$(mktemp -d -p /var/backups/ ejabberd-$TIME.XXXXXX)
	    chown ejabberd:ejabberd $BACKUPDIR
	    BACKUP=$BACKUPDIR/ejabberd-database
	    ctl backup $BACKUP
	    # Change ownership to root:root because ejabberd user might be
	    # removed on package removal.
	    chown -R root:root $BACKUPDIR
	    chmod 700 $BACKUPDIR
	    echo
	    echo The ejabberd database has been backed up to $BACKUP.
	    echo
	fi
    ;;

    deconfigure)
    ;;

    failed-upgrade)
    ;;

    *)
	echo "prerm called with unknown argument \`$1'" >&2
	exit 1
    ;;
esac

case "$1" in
    remove|purge)
        if ejabberdctl status >/dev/null || test $? = 1 ; then
            # Ejabberd is starting ($? = 1) or running ($? = 0)
	    invoke-rc.d ejabberd stop
	    pkill -u ejabberd
	fi
    ;;
esac

#DEBHELPER#

exit 0

